SELECTED_CHANNELS = [
  "5.uk",
  "5Star.uk",
  "5USA.uk",
  "5USAPlus1.uk",
  "BBCFourHD.uk",
  "BBCNews.uk",
  "BBCOneNorthWest.uk",
  "BBCParliament.uk",
  "BBCR1.uk",
  "BBCR1X.uk",
  "BBCR2.uk",
  "BBCR3.uk",
  "BBCR4EX.uk",
  "BBCR5L.uk",
  "BBCR5SX.uk",
  "BBCR6M.uk",
  "BBCRadioManchester.uk",
  "BBCRedButton1.uk",
  "BBCScotland.uk",
  "BBCThreeHD.uk",
  "BBCTwoHD.uk",
  "BBCWorldService.uk",
  "CBBC.uk",
  "CBeebies.uk",
  "CapitalRadio.uk",
  "CapitalXtra.uk",
  "Channel4North.uk",
  "ClassicFM.uk",
  "E4.uk",
  "E4Extra.uk",
  "E4HD.uk",
  "E4Plus1.uk",
  "Film4.uk",
  "Film4HD.uk",
  "Film4Plus1.uk",
  "ITV1Granada.uk",
  "ITV1Plus1Granada.uk",
  "ITV2.uk",
  "ITV2Plus1.uk",
  "ITV3.uk",
  "ITV3Plus1.uk",
  "ITV4.uk",
  "ITV4Plus1.uk",
  "ITVQuiz.uk",
  "LBCNews.uk",
  "LBCRadio.uk",
  "Legend.uk",
  "More4.uk",
  "More4HD.uk",
  "More4Plus1.uk",
  "Movies24.uk",
  "Movies24Plus.uk",
  "MustHaveIdeas.uk",
  "SkyArts.uk",
  "SkyMix.uk",
  "SkyNews.uk",
  "VirginRadio.uk"
]

class Channel < ActiveRecord::Base
  has_many :programmes, primary_key: "channel_id", foreign_key: "channel_id", dependent: :destroy

  def self.[](channel_id)
    find_by(channel_id: channel_id)
  end
end
